apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Ki
      # "kubectl get storageClass" to get the current available storageClasses
  storageClassName: hostpath

