apiVersion: v1
kind: Service
metadata:
  name: redis-server-node-port
spec:
  type: NodePort
  selector:
    component: redis-server
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 31515

